### ISSUE TITLE
How to set up as Docker driver

### ISSUE THREAD

**Issue by scnerd** [sepich/ceph-swarm#1]
This seems like a great idea and a phenomenal way to simplify the deployment of Ceph for/by a Swarm. I'm encountering a few issues getting this setup to work for me; assuming I can get the whole thing running properly and get a few OSD's running, how would I set up a driver so that I could  use this Ceph cluster to store Docker Swarm volumes? I was looking at Rexray, but it requires access to /etc/ceph on the docker host, which doesn't exist since that directory is stored and distributed as a swarm config. Maybe add another container that has access to the configs _and_ mounts /etc/ceph as a local volume?

**Comment by eleaner** [comment]
@scnerd 
Did you solve this problem?

**Comment by scnerd** [comment]
No, I didn't end up making progress on this. Ceph has since made available an official Helm for automagically deploying on Kubernetes, so I suspect that in most cases, that's probably a more complete and reliable solution.
